In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gs
import anatools.data as data
import anatools.analysis as ana
from sklearn.metrics import confusion_matrix
import sys
ana.start()
import gc
import warnings
warnings.filterwarnings('ignore')


# Pode Mudar:
basedir = '/home/matheus/cernbox/mestrado/HHDM/DESY/datasets'
list_basedir = os.listdir(basedir)
TreeName = 'selection'
period = '18'


# datasets = data.read_files(basedir, period) #Lendo todos os arquivos


In [2]:

datasets = {
    '2016': None,
    '2017': None,
    '2018': data.read_files(basedir, '18')
}


# Declare os nomes das amostras que vão estar dentro do datasets, para cada ano
simulation_samples = {
    '2016':['TTTo2L2Nu'],
    '2017':['TTTo2L2Nu'],
    '2018':['TTTo2L2Nu']
    }                       
data_samples = {
    # '2016':[''],
    # '2017':[''],
    '2018':['Data_A','Data_B','Data_C','Data_D']
}



helper_triggers = {
    '2016':[
        # 'HLT_PFMET200_HBHECleaned',
        # 'HLT_PFMET200_HBHE_BeamHaloCleaned',
        # 'HLT_PFMETTypeOne200_HBHE_BeamHaloCleaned',
        # 'HLT_PFMET120_PFMHT120_IDTight',
        # 'HLT_PFMET120_PFMHT120_IDTight_PFHT60',
        # 'HLT_PFHT500_PFMET100_PFMHT100_IDTight',
        # 'HLT_PFHT700_PFMET85_PFMHT85_IDTight',
        # 'HLT_PFHT800_PFMET75_PFMHT75_IDTight',
        # 'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight',
        # 'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60'
        ],
    '2017':[
        # 'HLT_PFMET200_HBHECleaned',
        # 'HLT_PFMET200_HBHE_BeamHaloCleaned',
        # 'HLT_PFMETTypeOne200_HBHE_BeamHaloCleaned',
        # 'HLT_PFMET120_PFMHT120_IDTight',
        # 'HLT_PFMET120_PFMHT120_IDTight_PFHT60',
        # 'HLT_PFHT500_PFMET100_PFMHT100_IDTight',
        # 'HLT_PFHT700_PFMET85_PFMHT85_IDTight',
        # 'HLT_PFHT800_PFMET75_PFMHT75_IDTight',
        # 'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight',
        # 'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60'
        ],
    '2018':[
        'HLT_PFMET200_HBHECleaned',
        'HLT_PFMET200_HBHE_BeamHaloCleaned',
        'HLT_PFMETTypeOne200_HBHE_BeamHaloCleaned',
        'HLT_PFMET120_PFMHT120_IDTight',
        'HLT_PFMET120_PFMHT120_IDTight_PFHT60',
        'HLT_PFHT500_PFMET100_PFMHT100_IDTight',
        'HLT_PFHT700_PFMET85_PFMHT85_IDTight',
        'HLT_PFHT800_PFMET75_PFMHT75_IDTight',
        'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight',
        'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60',
        'Met_triggers' #Variavel que diz se algum triggers foi ativado (OBRIGATORIO)
        ]
}
# Lista de triggers principais. Basta listar somente o que você usa, não a junção deles, pois essa tarefa é feita pela Classe
main_triggers = {
    '2016':[
        # 'HLT_IsoMu24',
        # 'HLT_Mu50',
        # 'HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8',
        # 'HLT_Ele32_WPTight_Gsf',
        # 'HLT_Ele115_CaloIdVT_GsfTrkIdT',
        # 'HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL',
        # 'HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ',
        # 'HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL',
        # 'HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL'
    ],
    '2017':[
        # 'HLT_IsoMu24',
        # 'HLT_Mu50',
        # 'HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8',
        # 'HLT_Ele32_WPTight_Gsf',
        # 'HLT_Ele115_CaloIdVT_GsfTrkIdT',
        # 'HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL',
        # 'HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ',
        # 'HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL',
        # 'HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL'
    ],
    '2018':[
        'HLT_IsoMu24',
        'HLT_Mu50',
        'HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8',
        'HLT_Ele32_WPTight_Gsf',
        'HLT_Ele115_CaloIdVT_GsfTrkIdT',
        'HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL',
        'HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ',
        'HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL',
        'HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL',
        'Lep_triggers' #VARIAVEL OBRIGATORIA, DEVIDO AO FATO DE NÂO SABER COMO VC CALCULA O Lep_triggers então tem que ter essa variavel
    ]
}


# Aqui você pode definir quantos canais você quiser, basta dizer o nome dele (que será usado para criar e salvar imagens e pastas) e o corte que define esse canal.
channels = {
    # 'All':'index == index',
    'MuMu':'( (RecoLepID == 13) or (RecoLepID > 31399 and RecoLepID <= 41300) or (RecoLepID > 41300 and RecoLepID <= 41399) )',
    'ElEl':'( (RecoLepID == 11) or (RecoLepID > 31100 and RecoLepID <= 31199) or (RecoLepID > 41100 and RecoLepID <= 41199) )',
    'ElMu':'( (RecoLepID > 1000) and (RecoLepID < 1999) )'
}

variables = {
    'MuMu':{
            "Lep_leading_eta": [0,0.5,1.5,2.4],
            "Lep_leading_pt":[40,60,80,100,200],
            "Lep_subleading_eta":[0,0.5,1.5,2.4],
            "Lep_subleading_pt":[20,25,200]
    },
    'ElEl':{
            "Lep_leading_eta": [0,0.5,1.5,2.4],
            "Lep_leading_pt":[40,60,80,100,200],
            "Lep_subleading_eta":[0,0.5,1.5,2.4],
            "Lep_subleading_pt":[20,35,200]
    },
    'ElMu':{
            "Muon_eta": [0,0.5,1.5,2.4],
            "Muon_pt":[20,30,40,60,200],
            "Electron_eta":[0,0.5,1.5,2.4],
            "Electron_pt":[20,30,40,60,200]
    }

}

variables_for_SF = {
    'MuMu':['Lep_leading_pt','Lep_subleading_pt'],
    'ElEl':['Lep_leading_pt','Lep_subleading_pt'],
    'ElMu':['Muon_pt','Electron_pt']
}


label_variaveis = {
        "Lep_leading_eta":r"$ Leading \ lepton \ \eta $",
        "Lep_leading_pt":r"$\mathrm{Leading\ } p_T^l\ [\mathrm{GeV}]$",
        "Lep_subleading_eta":r"$Subleading \ Lepton \ \eta $",
        "Lep_subleading_pt":r"$\mathrm{Subleading\ } p_T^l\ [\mathrm{GeV}]$",
        "Muon_eta":r"$ Electron \ lepton \ \eta $",
        "Muon_pt":r"$\mathrm{Muon\ } p_T^l\ [\mathrm{GeV}]$",
        "Electron_eta":r"$Electron \ Lepton \ \eta $",
        "Electron_pt":r"$\mathrm{Electron\ } p_T^l\ [\mathrm{GeV}]$" 
         
}





# Usadas para estudo de incertezas sistematicas!
regions = {
        'default':'index == index',
        'NJetsHigh':'Njets >= 3',
        'NJetsLow':'Njets < 3',
        'nPVHigh':'numPVs_ >= 30',
        'nPVLow':'numPVs_ <= 30',
        'METHigh':'MET_ >= 150',
        'METLow':'MET_ < 150',
        'ExtraMuon0':'nMuon == {}',
        'ExtraMuon1':'nMuon == {}',
        'ExtraMuon2':'nMuon == {}',
        'ExtraElectron0':'nElectron == {}',
        'ExtraElectron1':'nElectron == {}',
        'ExtraElectron2':'nElectron == {}',
        'DeltaRZone0':'0.3 > LepLep_deltaR',
        'DeltaRZone1':'0.8 > LepLep_deltaR >= 0.3',
        'DeltaRZone2':'2 > LepLep_deltaR >= 0.8',
        'DeltaRZone3':'LepLep_deltaR >= 2' 
    }

data_sample_lumi = {
    '2016' : {
        # 'Data_A':0.23480886,
        # 'Data_B':0.11828733,
        # 'Data_C':0.115479605,
        # 'Data_D':0.531424197
    },
    '2017' : {
        # 'Data_A':0.23480886,
        # 'Data_B':0.11828733,
        # 'Data_C':0.115479605,
        # 'Data_D':0.531424197
    },
    '2018' : {
        'Data_A':0.23480886,
        'Data_B':0.11828733,
        'Data_C':0.115479605,
        'Data_D':0.531424197
    }
}



Loading datasets...


100%|██████████| 7/7 [00:11<00:00,  1.68s/it]


In [3]:
#importanto a classe HEPTrigger
from Class_HepTrigger import HepTrigger
#Usando o objeto
objeto = HepTrigger(
    datasets,
    simulation_samples=simulation_samples,
    data_samples=data_samples,
    main_triggers=main_triggers,
    helper_triggers=helper_triggers,
    channels=channels,
    variables=variables,
    label_variaveis=label_variaveis,
    variables_for_SF=variables_for_SF,
    regions = regions,
    data_lumi = data_sample_lumi     
)


In [10]:
# objeto.do_all_the_alfas_plots_of_all_triggers()
# objeto.get_alfa_value(sample='All_simulation',channel='MuMu',year='2018',trigg_1='fired_any_main_trigger',trigg_2='fired_any_helper_trigger',show=True)
# objeto.do_hist_of_number_of_events_pass_of_each_main_trigger()
# objeto.do_all_the_plots_of_N_eff()
# objeto.do_hist_of_number_of_events_pass_of_each_helper_trigger()
# objeto.do_all_eff_trigger_of_simulation_in_comparation_with_data()

# objeto.get_eff_trigger_of_simulation_and_data(year='2018',sample='All_simulation',channel='MuMu',var='Lep_leading_pt',show=True)

# objeto.get_the_diff_between_SF_default_and_SF_of_all_eras(year='2018',channel='MuMu',var_x='Lep_leading_pt',var_y='Lep_subleading_pt')

objeto.get_all_SF_systemic_error_of_2D_varibles_for_simulation()

# objeto.get_the_diff_between_SF_default_and_SF_of_different_regions(year='2018',channel='ElMu',var_x='Muon_pt',var_y='Electron_pt')


No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that 

err_Alpha 0.0008986582372174645
err_eras [[9.18136114e-04 1.27703027e-04]
 [1.09032665e-03 1.13187762e-06]
 [8.07226194e-03 1.22672776e-04]
 [1.65731685e-04 9.10353600e-05]]
err_regions [[0.0346827  0.0114443 ]
 [0.03353292 0.00406937]
 [0.05660667 0.00733178]
 [0.02346138 0.09545011]]
[[0.03470649 0.01148024]
 [0.03356267 0.00416742]
 [0.0571864  0.00738767]
 [0.02347917 0.09545438]]


No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that 

err_Alpha 0.0010631847281086237
err_eras [[6.03120158e-04 8.64922098e-05]
 [1.89622650e-04 6.43243246e-04]
 [9.14106580e-04 1.88796927e-04]
 [7.15358532e-05 4.35583432e-05]]
err_regions [[0.03290766 0.01592543]
 [0.02279166 0.00875871]
 [0.0127055  0.01604214]
 [0.02516106 0.07823975]]
[[0.03293035 0.01596112]
 [0.02281723 0.00884642]
 [0.01278263 0.01607844]
 [0.02518361 0.07824699]]


No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that 

err_Alpha 0.0031358331141406737
err_eras [[           nan            nan 7.34976237e-05 4.16868094e-04]
 [           nan            nan 1.22115239e-04 6.40445567e-05]
 [2.53782362e-03 1.16471473e-04 4.87143447e-04 2.20912029e-04]
 [9.49739976e-04 5.40679222e-04 1.90994426e-04 5.01613234e-04]]
err_regions [[0.         0.         0.03140934 0.00814362]
 [0.         0.         0.00703926 0.00437156]
 [0.0370636  0.03294776 0.0069962  0.00673187]
 [0.00652507 0.01161197 0.03682977 0.02799102]]
[[0.         0.         0.03156558 0.00873646]
 [0.         0.         0.00770711 0.00538034]
 [0.03728249 0.03309686 0.00768229 0.00742969]
 [0.00730151 0.01204008 0.03696352 0.02817059]]


In [5]:

# objeto.get_eff_trigger_of_simulation_and_data(datasets=datasets,sample='All_simulation',year='2018',channel='MuMu',var='Lep_leading_pt',show=True)
# objeto.do_all_eff_trigger_of_simulation_in_comparation_with_data(datasets)
# datasets['2018']['All_simulation'].head()
# objeto.do_all_the_plots_of_N_eff(datasets)
# objeto._get_N_eff_of_the_bins(datasets=datasets,sample = 'All_simulation',year='2018',channel='MuMu',var='Lep_leading_pt')

# objeto.do_2D_of_all_number_of_events_per_bin(datasets=datasets)

# both = objeto.get_2D_number_of_events_per_bin(datasets=datasets,year='2018',sample='All_simulation',channel='MuMu',var_x='Lep_leading_pt',var_y='Lep_subleading_pt',show=False,events_that_already_fired_what_trigg='helper')
# met = objeto.get_2D_number_of_events_per_bin(datasets=datasets,year='2018',sample='All_simulation',channel='MuMu',var_x='Lep_leading_pt',var_y='Lep_subleading_pt',show=False,events_that_already_fired_what_trigg='no_one')

# print(both/met)




In [6]:
# data_2018['Data_A'].dtypes
# import sys

# print(sys.getsizeof(True))   # 28 bytes
# print(sys.getsizeof(False))  # 24 bytes
# print(sys.getsizeof(0))      # 24 bytes
# print(sys.getsizeof(1))      # 28 bytes
# print(sys.getsizeof(100000000000))    # 28 bytes


# from pympler import muppy, summary
# from pympler import asizeof, muppy
# import pandas as pd

# # Calcula o tamanho ocupado por cada dataframe e os mostra na tela
# # Lista todos os objetos em memória
# all_objects = muppy.get_objects()



# # Filtra apenas os objetos que são instâncias de DataFrame
# dataframes = [obj for obj in all_objects if isinstance(obj, pd.DataFrame)]

# # Calcula o tamanho ocupado por cada dataframe e os mostra na tela
# print("Tamanhos ocupados pelos DataFrames:")
# for df in dataframes:
#     size = asizeof.asizeof(df)
#     size_str = '{:.2f} MB'.format(size / (1024 * 1024))
#     print(f"{type(df)}: {size_str}")


# # Tamanhos ocupados pelos DataFrames:
# <class 'pandas.core.frame.DataFrame'>: 4.51 MB
# <class 'pandas.core.frame.DataFrame'>: 8.44 MB
# <class 'pandas.core.frame.DataFrame'>: 36.72 MB
# <class 'pandas.core.frame.DataFrame'>: 4.86 MB
# <class 'pandas.core.frame.DataFrame'>: 22.15 MB
# <class 'pandas.core.frame.DataFrame'>: 2219.27 MB
# <class 'pandas.core.frame.DataFrame'>: 2697.73 MB
# <class 'pandas.core.frame.DataFrame'>: 39.08 MB
# <class 'pandas.core.frame.DataFrame'>: 2697.73 MB


In [7]:
# def my_reset(*varnames):
#     """
#     varnames are what you want to keep
#     """
#     globals_ = globals()
#     to_save = {v: globals_[v] for v in varnames}
#     to_save['my_reset'] = my_reset  # lets keep this function by default
#     del globals_
#     get_ipython().magic("reset")
#     globals().update(to_save)

In [8]:
# my_reset('data_2018')

In [9]:
# data_2018.keys()